# Docker setup for frontend and backend services
# Frontend runs on port 3000, backend on port 5000
# Use volumes for live development

version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: meliorism_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: meliorism_foundation
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - meliorism_network

  # Backend Service
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: meliorism_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/meliorism_foundation?authSource=admin
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - meliorism_network
    command: npm run dev

  # Frontend Service
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: meliorism_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_PAYSTACK_PUBLIC_KEY=pk_test_your_paystack_public_key
      - REACT_APP_FLUTTERWAVE_PUBLIC_KEY=FLWPUBK_TEST-your_flutterwave_public_key
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - meliorism_network
    command: npm start

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: meliorism_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - meliorism_network

volumes:
  mongodb_data:
    driver: local

networks:
  meliorism_network:
    driver: bridge